### ISSUE TITLE
Criar propriedade Wikidata para código de localidade do INE

### ISSUE THREAD

**Issue by vgeorge** [mapaslivres/divisoes-administrativas-pt#1]
Ao que parece não há uma propriedade para atribuir o código INE a localidades de Portugal no Wikidata. Para poder comparar com os dados do INE neste repositório, é preciso criar a propriedade de começar a cadastrar as localidades. Exemplo de códigos em outros países:

- México: [código INEGI](https://www.wikidata.org/wiki/Property:P1976) 
- Brasil: [código IBGE](https://www.wikidata.org/wiki/Property:P1585)

**Comment by nicolasmaia** [comment]
Aqui vai mais detalhes: https://www.wikidata.org/wiki/Wikidata:Property_proposal

**Comment by vgeorge** [comment]
@picsi obrigado. Criei um item que descreve o código:

https://www.wikidata.org/wiki/Q60059245

Depois temos que pedir a criação da propriedade. Eu acho que ela tem que ser mais abrangente do que a do Brasil citada acima, pois esta refere-se apenas a municípios, sendo que o código IBGE tem vários níveis administrativos. Aqui tem definição oficial do INE quanto a isso:

https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_cont_inst&INST=6251013&xlang=pt

**Comment by Ederporto** [comment]
Olá, @vgeorge e @picsi , propriedade proposta, por favor, façam as alterações que julgarem necessárias: https://www.wikidata.org/wiki/Wikidata:Property_proposal/Generic#Identificador_INE_(Portugal)

**Comment by vgeorge** [comment]
A proposta foi aprovada: 🎉

https://www.wikidata.org/wiki/Property:P6324
